# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/wugy/crypto/WIB_IPFE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/wugy/crypto/WIB_IPFE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/wugy/crypto/WIB_IPFE/CMakeFiles /root/wugy/crypto/WIB_IPFE//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/wugy/crypto/WIB_IPFE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IPFE_test_ibbe

# Build rule for target.
IPFE_test_ibbe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IPFE_test_ibbe
.PHONY : IPFE_test_ibbe

# fast build rule for target.
IPFE_test_ibbe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/build
.PHONY : IPFE_test_ibbe/fast

cjson/cJSON.o: cjson/cJSON.c.o
.PHONY : cjson/cJSON.o

# target to build an object file
cjson/cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/cjson/cJSON.c.o
.PHONY : cjson/cJSON.c.o

cjson/cJSON.i: cjson/cJSON.c.i
.PHONY : cjson/cJSON.i

# target to preprocess a source file
cjson/cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/cjson/cJSON.c.i
.PHONY : cjson/cJSON.c.i

cjson/cJSON.s: cjson/cJSON.c.s
.PHONY : cjson/cJSON.s

# target to generate assembly for a file
cjson/cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/cjson/cJSON.c.s
.PHONY : cjson/cJSON.c.s

src/components/CipherText.o: src/components/CipherText.cpp.o
.PHONY : src/components/CipherText.o

# target to build an object file
src/components/CipherText.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/components/CipherText.cpp.o
.PHONY : src/components/CipherText.cpp.o

src/components/CipherText.i: src/components/CipherText.cpp.i
.PHONY : src/components/CipherText.i

# target to preprocess a source file
src/components/CipherText.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/components/CipherText.cpp.i
.PHONY : src/components/CipherText.cpp.i

src/components/CipherText.s: src/components/CipherText.cpp.s
.PHONY : src/components/CipherText.s

# target to generate assembly for a file
src/components/CipherText.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/components/CipherText.cpp.s
.PHONY : src/components/CipherText.cpp.s

src/components/ElementList.o: src/components/ElementList.cpp.o
.PHONY : src/components/ElementList.o

# target to build an object file
src/components/ElementList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/components/ElementList.cpp.o
.PHONY : src/components/ElementList.cpp.o

src/components/ElementList.i: src/components/ElementList.cpp.i
.PHONY : src/components/ElementList.i

# target to preprocess a source file
src/components/ElementList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/components/ElementList.cpp.i
.PHONY : src/components/ElementList.cpp.i

src/components/ElementList.s: src/components/ElementList.cpp.s
.PHONY : src/components/ElementList.s

# target to generate assembly for a file
src/components/ElementList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/components/ElementList.cpp.s
.PHONY : src/components/ElementList.cpp.s

src/components/MasterKey.o: src/components/MasterKey.cpp.o
.PHONY : src/components/MasterKey.o

# target to build an object file
src/components/MasterKey.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/components/MasterKey.cpp.o
.PHONY : src/components/MasterKey.cpp.o

src/components/MasterKey.i: src/components/MasterKey.cpp.i
.PHONY : src/components/MasterKey.i

# target to preprocess a source file
src/components/MasterKey.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/components/MasterKey.cpp.i
.PHONY : src/components/MasterKey.cpp.i

src/components/MasterKey.s: src/components/MasterKey.cpp.s
.PHONY : src/components/MasterKey.s

# target to generate assembly for a file
src/components/MasterKey.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/components/MasterKey.cpp.s
.PHONY : src/components/MasterKey.cpp.s

src/components/PublicKey.o: src/components/PublicKey.cpp.o
.PHONY : src/components/PublicKey.o

# target to build an object file
src/components/PublicKey.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/components/PublicKey.cpp.o
.PHONY : src/components/PublicKey.cpp.o

src/components/PublicKey.i: src/components/PublicKey.cpp.i
.PHONY : src/components/PublicKey.i

# target to preprocess a source file
src/components/PublicKey.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/components/PublicKey.cpp.i
.PHONY : src/components/PublicKey.cpp.i

src/components/PublicKey.s: src/components/PublicKey.cpp.s
.PHONY : src/components/PublicKey.s

# target to generate assembly for a file
src/components/PublicKey.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/components/PublicKey.cpp.s
.PHONY : src/components/PublicKey.cpp.s

src/components/SecretKey.o: src/components/SecretKey.cpp.o
.PHONY : src/components/SecretKey.o

# target to build an object file
src/components/SecretKey.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/components/SecretKey.cpp.o
.PHONY : src/components/SecretKey.cpp.o

src/components/SecretKey.i: src/components/SecretKey.cpp.i
.PHONY : src/components/SecretKey.i

# target to preprocess a source file
src/components/SecretKey.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/components/SecretKey.cpp.i
.PHONY : src/components/SecretKey.cpp.i

src/components/SecretKey.s: src/components/SecretKey.cpp.s
.PHONY : src/components/SecretKey.s

# target to generate assembly for a file
src/components/SecretKey.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/components/SecretKey.cpp.s
.PHONY : src/components/SecretKey.cpp.s

src/curve/params.o: src/curve/params.cpp.o
.PHONY : src/curve/params.o

# target to build an object file
src/curve/params.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/curve/params.cpp.o
.PHONY : src/curve/params.cpp.o

src/curve/params.i: src/curve/params.cpp.i
.PHONY : src/curve/params.i

# target to preprocess a source file
src/curve/params.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/curve/params.cpp.i
.PHONY : src/curve/params.cpp.i

src/curve/params.s: src/curve/params.cpp.s
.PHONY : src/curve/params.s

# target to generate assembly for a file
src/curve/params.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/curve/params.cpp.s
.PHONY : src/curve/params.cpp.s

src/schemes/ibbe_pk_ipfe.o: src/schemes/ibbe_pk_ipfe.cpp.o
.PHONY : src/schemes/ibbe_pk_ipfe.o

# target to build an object file
src/schemes/ibbe_pk_ipfe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/schemes/ibbe_pk_ipfe.cpp.o
.PHONY : src/schemes/ibbe_pk_ipfe.cpp.o

src/schemes/ibbe_pk_ipfe.i: src/schemes/ibbe_pk_ipfe.cpp.i
.PHONY : src/schemes/ibbe_pk_ipfe.i

# target to preprocess a source file
src/schemes/ibbe_pk_ipfe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/schemes/ibbe_pk_ipfe.cpp.i
.PHONY : src/schemes/ibbe_pk_ipfe.cpp.i

src/schemes/ibbe_pk_ipfe.s: src/schemes/ibbe_pk_ipfe.cpp.s
.PHONY : src/schemes/ibbe_pk_ipfe.s

# target to generate assembly for a file
src/schemes/ibbe_pk_ipfe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/schemes/ibbe_pk_ipfe.cpp.s
.PHONY : src/schemes/ibbe_pk_ipfe.cpp.s

src/utils/func.o: src/utils/func.cpp.o
.PHONY : src/utils/func.o

# target to build an object file
src/utils/func.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/utils/func.cpp.o
.PHONY : src/utils/func.cpp.o

src/utils/func.i: src/utils/func.cpp.i
.PHONY : src/utils/func.i

# target to preprocess a source file
src/utils/func.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/utils/func.cpp.i
.PHONY : src/utils/func.cpp.i

src/utils/func.s: src/utils/func.cpp.s
.PHONY : src/utils/func.s

# target to generate assembly for a file
src/utils/func.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/src/utils/func.cpp.s
.PHONY : src/utils/func.cpp.s

unit_test/test_ibbe.o: unit_test/test_ibbe.cpp.o
.PHONY : unit_test/test_ibbe.o

# target to build an object file
unit_test/test_ibbe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/unit_test/test_ibbe.cpp.o
.PHONY : unit_test/test_ibbe.cpp.o

unit_test/test_ibbe.i: unit_test/test_ibbe.cpp.i
.PHONY : unit_test/test_ibbe.i

# target to preprocess a source file
unit_test/test_ibbe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/unit_test/test_ibbe.cpp.i
.PHONY : unit_test/test_ibbe.cpp.i

unit_test/test_ibbe.s: unit_test/test_ibbe.cpp.s
.PHONY : unit_test/test_ibbe.s

# target to generate assembly for a file
unit_test/test_ibbe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPFE_test_ibbe.dir/build.make CMakeFiles/IPFE_test_ibbe.dir/unit_test/test_ibbe.cpp.s
.PHONY : unit_test/test_ibbe.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... IPFE_test_ibbe"
	@echo "... cjson/cJSON.o"
	@echo "... cjson/cJSON.i"
	@echo "... cjson/cJSON.s"
	@echo "... src/components/CipherText.o"
	@echo "... src/components/CipherText.i"
	@echo "... src/components/CipherText.s"
	@echo "... src/components/ElementList.o"
	@echo "... src/components/ElementList.i"
	@echo "... src/components/ElementList.s"
	@echo "... src/components/MasterKey.o"
	@echo "... src/components/MasterKey.i"
	@echo "... src/components/MasterKey.s"
	@echo "... src/components/PublicKey.o"
	@echo "... src/components/PublicKey.i"
	@echo "... src/components/PublicKey.s"
	@echo "... src/components/SecretKey.o"
	@echo "... src/components/SecretKey.i"
	@echo "... src/components/SecretKey.s"
	@echo "... src/curve/params.o"
	@echo "... src/curve/params.i"
	@echo "... src/curve/params.s"
	@echo "... src/schemes/ibbe_pk_ipfe.o"
	@echo "... src/schemes/ibbe_pk_ipfe.i"
	@echo "... src/schemes/ibbe_pk_ipfe.s"
	@echo "... src/utils/func.o"
	@echo "... src/utils/func.i"
	@echo "... src/utils/func.s"
	@echo "... unit_test/test_ibbe.o"
	@echo "... unit_test/test_ibbe.i"
	@echo "... unit_test/test_ibbe.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

